#!/usr/bin/env node
// corp-version: 2026-08-26.8
// gen-index.mjs — generates openspec/index.json + index.md from openspec/specs/ (+ optional build/modules.txt).
// Deterministic across machines: byte-wise sort (no locale), digest built from sorted content,
// repo name from committed openspec/repo.txt (never from the checkout folder name).
// --check: regenerate in memory and diff against committed files; exit 1 on drift.
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, resolve, basename } from 'node:path';
import { createHash } from 'node:crypto';

const CHECK = process.argv.includes('--check');
const ROOT = resolve(process.argv.filter(a => !a.startsWith('--'))[2] ?? '.');
const osDir = join(ROOT, 'openspec');
const specsDir = join(osDir, 'specs');
const repoTxt = join(osDir, 'repo.txt');

// repo identity is committed data, not the folder name (CI workspaces, worktrees, renamed clones)
const repoName = existsSync(repoTxt) ? readFileSync(repoTxt, 'utf8').trim() : basename(ROOT);

const byId = (a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0); // byte-wise, locale-independent
const caps = [];
const texts = {};
if (existsSync(specsDir)) {
  for (const d of readdirSync(specsDir, { withFileTypes: true }).filter(e => e.isDirectory())) {
    const specPath = join(specsDir, d.name, 'spec.md');
    if (!existsSync(specPath)) continue; // dirs without spec.md are corp-lint's problem, not the index's
    const txt = readFileSync(specPath, 'utf8');
    texts[d.name] = txt;
    const title = txt.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? d.name;
    const summary = (txt.split('\n').find(l => l.trim() && !l.startsWith('#')) ?? '').trim().slice(0, 200);
    caps.push({ id: d.name, title, path: `openspec/specs/${d.name}/spec.md`, summary });
  }
}
caps.sort(byId);

let modules = [];
const modFile = join(ROOT, 'build', 'modules.txt'); // produced by the build: mvn/gradle module list
if (existsSync(modFile)) {
  modules = readFileSync(modFile, 'utf8').split('\n').map(s => s.trim()).filter(Boolean).sort(); // default sort = code-unit order
}

// digest over SORTED content so filesystem readdir order can never change it
const digestInput = [repoName, ...caps.map(c => c.id + '\x00' + texts[c.id]), ...modules];
const index = {
  schema_version: 1,
  repo: repoName,
  source_digest: createHash('sha256').update(digestInput.join('\x01')).digest('hex').slice(0, 16),
  capabilities: caps,
  ...(modules.length ? { modules } : {}),
};
const json = JSON.stringify(index, null, 2) + '\n';

const md = [
  `# ${index.repo} — capability index`,
  '',
  `> GENERATED by tools/gen-index.mjs — do not edit. digest: ${index.source_digest}`,
  '',
  ...caps.map(c => `- [${c.title}](${c.path.replace(/^openspec\//, '')}) — ${c.summary}`),
  ...(modules.length ? ['', '## Modules', '', ...modules.map(m => `- ${m}`)] : []),
  '',
].join('\n');

const jsonPath = join(osDir, 'index.json');
const mdPath = join(osDir, 'index.md');

if (CHECK) {
  const cur = f => (existsSync(f) ? readFileSync(f, 'utf8') : '');
  if (cur(jsonPath) !== json || cur(mdPath) !== md) {
    console.error('✗ index drift: openspec/index.* does not match current specs');
    console.error('  ↳ run: node tools/gen-index.mjs && git add openspec/index.json openspec/index.md openspec/repo.txt');
    process.exit(1);
  }
  console.log('✓ index up to date');
} else {
  mkdirSync(osDir, { recursive: true });
  if (!existsSync(repoTxt)) writeFileSync(repoTxt, repoName + '\n'); // pin identity on first run — commit it
  writeFileSync(jsonPath, json);
  writeFileSync(mdPath, md);
  console.log(`✓ wrote openspec/index.json + index.md (${caps.length} capabilities, digest ${index.source_digest})`);
}
