import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { LAYOUT } from './layout.mjs';

const MARKER = 'serpens-sdd shim — generated; do not edit.';

/**
 * First line of every `lefthook.yml` (or `serpens/lefthook.yml` fallback) this kit writes.
 * Read back by the stage 5 ownership check to tell "ours, safe to regenerate" from "a team's own
 * file, however it is named" — see gap 8 in serpens-openspec-coexistence-gaps-2026-09-22.md.
 */
export const LEFTHOOK_MARKER = '# serpens-sdd:generated — do not edit; regenerated by serpens-sdd init';

/**
 * Every "main config" name lefthook itself will read, in the order lefthook's own docs list
 * them (lefthook `docs/configuration/README.md`, v2.1.14): three base names (bare, dot-prefixed,
 * under `.config/`) times five extensions. "More than one present and you'll never know which
 * one wins" is upstream's own wording — this is why stage 5 must never write `lefthook.yml`
 * blind.
 */
export const LEFTHOOK_MAIN_CONFIG_NAMES = (() => {
  const bases = ['lefthook', '.lefthook', '.config/lefthook'];
  const exts = ['yml', 'yaml', 'toml', 'json', 'jsonc'];
  const names = [];
  for (const base of bases) {
    for (const ext of exts) names.push(`${base}.${ext}`);
  }
  return names;
})();

/** Per-developer override names, conventionally git-ignored — never a team gate's home, but
 * still a config lefthook merges, so an ownership check must at least know one is present. */
const LEFTHOOK_LOCAL_NAMES = ['lefthook-local.yml'];

/**
 * Every lefthook config file already present in `repoRoot` — every main config name lefthook
 * itself would read, plus any local-override file. Order matches `LEFTHOOK_MAIN_CONFIG_NAMES`
 * followed by `LEFTHOOK_LOCAL_NAMES`.
 * @param {string} repoRoot
 * @returns {string[]}
 */
export function findLefthookConfigs(repoRoot) {
  const found = [];
  for (const name of [...LEFTHOOK_MAIN_CONFIG_NAMES, ...LEFTHOOK_LOCAL_NAMES]) {
    if (existsSync(join(repoRoot, name))) found.push(name);
  }
  return found;
}

/**
 * The one canonical way to call the generated shim: `<repo>/serpens/bin/serpens-sdd`, with the repository
 * root resolved at run time by git so the string is correct from any working directory and in a
 * user-scoped command file shared across repositories. This is the single source of truth for
 * BOTH substitution sites — the `<serpens-sdd>` token in every installed command and skill (stage 6)
 * and the `run:` lines of the generated `lefthook.yml` (stage 5) — so an install can never
 * disagree with itself about how it calls the package.
 */
export const SHIM_INVOCATION = `"$(git rev-parse --show-toplevel)"/${LAYOUT.shim}`;

/**
 * POSIX-sh single-quote a path so nothing inside it is ever expanded by the shell. The only
 * character that needs handling inside single quotes is `'` itself, closed and re-opened as
 * `'\''`.
 * @param {string} value
 * @returns {string}
 */
export function shQuote(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

/**
 * Write the language-agnostic POSIX-sh shim at <repoRoot>/serpens/bin/serpens-sdd.
 * Never overwrites a file at that path that isn't a shim it generated.
 * Never creates repoRoot itself — only serpens/bin/ within an already-existing repoRoot.
 * @param {string} repoRoot
 * @param {{binPath: string}} opts - absolute path of bin/serpens-sdd.mjs
 * @returns {string} the shim path
 */
export function writeShim(repoRoot, { binPath }) {
  if (!existsSync(repoRoot)) {
    const err = new Error(`repoRoot does not exist: ${repoRoot}`);
    err.exitCode = 3;
    throw err;
  }

  const shimPath = join(repoRoot, LAYOUT.shim);
  const toolsDir = dirname(shimPath);

  if (existsSync(shimPath)) {
    const existing = readFileSync(shimPath, 'utf8');
    if (!existing.includes(MARKER)) {
      throw new Error(`refusing to overwrite ${shimPath}: not a serpens-sdd generated shim`);
    }
  }

  if (existsSync(toolsDir) && !statSync(toolsDir).isDirectory()) {
    throw new Error(`cannot create ${LAYOUT.shim} directory, a file already exists at ${toolsDir}`);
  }
  if (!existsSync(toolsDir)) mkdirSync(toolsDir, { recursive: true });

  // Both paths are SINGLE-quoted and escaped: a `$`, a backtick or a `"` anywhere in the
  // installed path (or in the node executable's path) would otherwise be expanded by /bin/sh
  // and yield a broken hook in every repository that got this shim.
  const body = `#!/bin/sh
# ${MARKER} Routes to the installed package, no registry access.
exec ${shQuote(process.execPath)} ${shQuote(binPath)} "$@"
`;
  writeFileSync(shimPath, body, 'utf8');
  chmodSync(shimPath, 0o755);
  return shimPath;
}


/**
 * Decide which of the three call routes a repository should use.
 * The shim is the default for every repository, whatever language it is written in,
 * whenever a shim is available. Otherwise fall back to node_modules/.bin (only when the
 * repository already has a package.json), and last to npx --no-install, which fails fast
 * rather than installing mid-commit.
 * @param {{repoRoot: string, hasNodeModules: boolean, shimAvailable?: boolean}} opts
 * @returns {{route: string, invocation: string}}
 */
export function resolveCallRoute({ repoRoot, hasNodeModules, shimAvailable = true }) {
  void repoRoot;
  if (shimAvailable) {
    return { route: 'shim', invocation: SHIM_INVOCATION };
  }
  if (hasNodeModules) {
    return { route: 'node_modules', invocation: 'node_modules/.bin/serpens-sdd' };
  }
  return { route: 'npx', invocation: 'npx --no-install @fresh-fx59/serpens-sdd' };
}

const LEFTHOOK_COMMENTS = {
  en: {
    serpensDocsScope: `      # --staged-scope: skip when nothing staged is Serpens-owned (a vanilla OpenSpec commit) —
      # gap 1, serpens-openspec-coexistence-gaps-2026-09-22.md. The agent's own HARD RULE and CI
      # still run plain \`verify-docs\` (no flag), always the full gate.`,
    branchConvention: `    # The branch name is checked HERE as well as on push, and this is the copy that always runs.
    # lefthook skips any pre-push command when the push carries no files it can list — which is
    # exactly the push that publishes a brand-new branch, the first time the name matters. Verified
    # in lefthook's own build_command.go: \`SkipError{"no matching push files"}\`, with no YAML-level
    # override (only \`lefthook run pre-push --force\`). A commit always has staged files, so this
    # copy cannot be skipped, and a bad branch name is refused before the first commit lands on it.`,
    commitMsgArg: `      # {1} is the commit-message file lefthook passes through.`,
    prePushBackstop: `      # Backstop only — see the pre-commit note; this one is skipped on a new-branch push.`,
  },
  ru: {
    serpensDocsScope: `      # --staged-scope: пропуск, если ничего из staged не принадлежит Serpens (обычный коммит OpenSpec) —
      # gap 1, serpens-openspec-coexistence-gaps-2026-09-22.md. HARD RULE агента и CI по-прежнему
      # запускают обычный \`verify-docs\` (без флага) — полную проверку всегда.`,
    branchConvention: `    # Имя ветки проверяется ЗДЕСЬ и при push — и это копия, которая срабатывает всегда.
    # lefthook пропускает pre-push команду, если push не несёт файлов, которые он может
    # перечислить, — а это ровно тот push, который публикует совсем новую ветку, когда имя
    # впервые имеет значение. Проверено в build_command.go самого lefthook:
    # \`SkipError{"no matching push files"}\`, без переопределения на уровне YAML (только
    # \`lefthook run pre-push --force\`). У коммита staged-файлы есть всегда, так что эта копия
    # пропущена быть не может, и плохое имя ветки отклоняется ещё до первого коммита в неё.`,
    commitMsgArg: `      # {1} — файл сообщения коммита, который передаёт lefthook.`,
    prePushBackstop: `      # Только страховка — см. заметку у pre-commit; эта копия пропускается при push новой ветки.`,
  },
};

const LEFTHOOK_EXTENDS_NOTE = {
  en: '# A repository with its own lefthook config gets this file at serpens/lefthook.yml instead, plus an `extends:` line to add by hand — never a silent overwrite.',
  ru: '# У репозитория со своим конфигом lefthook этот файл попадёт в serpens/lefthook.yml, плюс строка `extends:` для ручного добавления — без молчаливой перезаписи.',
};

/**
 * YAML single-quote a scalar (`'` doubled inside). Every generated `run:` value goes through
 * this: the shim invocation begins with a double-quoted `"$(git rev-parse --show-toplevel)"`
 * followed by more text, which YAML rejects as a plain or double-quoted scalar — real lefthook
 * 2.1.4 refused the whole file (`yaml: line 8: did not find expected key`, step-6 repro,
 * 2026-09-23). Single quotes keep every character literal for the shell lefthook hands it to.
 * @param {string} value
 * @returns {string}
 */
export function yamlSingleQuote(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

/**
 * Render the lefthook config, reproducing kits/<lang>/config/lefthook.yml.example verbatim
 * (including its comments), with each `<serpens-sdd> <subcommand>` placeholder replaced by the
 * resolved invocation. The YAML structure and every `run:` line are identical across
 * languages; only the inline comments differ, taken verbatim from each kit's own example.
 * @param {string} invocation
 * @param {'en'|'ru'} [lang]
 * @returns {string}
 */
export function renderLefthook(invocation, lang = 'en') {
  const c = LEFTHOOK_COMMENTS[lang] ?? LEFTHOOK_COMMENTS.en;
  const q = (sub) => yamlSingleQuote(`${invocation} ${sub}`);
  return `${LEFTHOOK_MARKER}
pre-commit:
  parallel: true
  commands:
    serpens-docs:
${c.serpensDocsScope}
      run: ${q('verify-docs --staged-scope')}
${c.branchConvention}
    serpens-branch:
      run: ${q('git-naming --branch')}

commit-msg:
  commands:
    serpens-commit-msg:
${c.commitMsgArg}
      run: ${q('git-naming --commit-msg {1}')}

pre-push:
  commands:
    serpens-branch:
${c.prePushBackstop}
      run: ${q('git-naming --branch')}

${LEFTHOOK_EXTENDS_NOTE[lang] ?? LEFTHOOK_EXTENDS_NOTE.en}
`;
}
